version: "2"

services:
  mysqldb:
    image: mysql:8-oracle

    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=hobbie_backend_db

  spring-backend:
    image: spring-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1010:1010"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/hobbie_backend_db?useSSL=false&serverTimezone=Europe/Paris
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

spring-frontend:
    image: spring-backend:v1
    ports:
      - "4200:4200"

  
networks:
  springmysql-net:
